name: publish

on:
  push:
    branches:
      - gh-pages
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: setup bun
        uses: oven-sh/setup-bun@v1
        with:
            bun-version: "1.0.25"
      - name: Install bun
        run: bun install
      - name: Install vite-ssg
        run: bun add vite @hono/vite-ssg
      - name: Build project
        run: bun run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist